# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509853ad206098c5f23b9dfbc019347a13a09910812fa457fd25cdaf90041253d6e243c2467d66a83990b2f56c737a77285edc2582f585f480d24ed9283c8275

test:
  secret_key_base: e25921693298ab288edf598ac44a8548b9179f02dac0d17e1e22c587dc7a8ce34bfce7b6a46bc5a2ffda93d2595f49fe4f826afc2f327a494981489ddfa73662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
